[package]
name = "runnit"
description = "Run all commands that come in through stdin"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"
license = "MIT"

[dependencies]
regex = "1.5.5"
subprocess = "0.1.18"
