[package]
name = "runnit"
description = "Run all commands that come in through stdin"
version = "0.1.0"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
edition = "2018"
license = "MIT"

[dependencies]
cached = "0.9.0"
regex = "1.3.1"
subprocess = "0.1.18"
